### ISSUE TITLE
Concurency issue ?

### ISSUE THREAD

**Issue by jcajkovic** [malice-plugins/avast#2]
I've troubles when load testing the web part of this service. When I run python test script randomly choosing files from one directory where is mix of the infected (eicar) and not infected files sending to the service and I have only one instance of the script running (sequential delivery) everything is ok. However when I run multiple instances of this test in 10 minutes I got response that the file is infected with note that that is EICAR NOT VIRUS file however file sent is eligible not infected. So we got the inconsistent results. 

Test Script (Python):
```
import requests
import random
import time
from timeit import default_timer as timer
import json
import os
from elasticsearch import Elasticsearch
import uuid
from datetime import datetime

url = "https://<url>/scan"

path = "../testfiles"

items = [f for f in os.listdir(path) if os.path.isfile( os.path.join(path, f) )]

print len(items)

def runVirusScanTest(path):
    start = timer()

    multipart_form_data = {
        'malware': open(path, 'rb')
    }

    try:
        response = requests.post(url, files=multipart_form_data)
        end = timer()

        string = response.text.decode('utf-8')
        print string
        json_obj = json.loads(string)

        data = {
            'timestamp': datetime.now(),
            'time_elapsed': end-start,
            'filepath': path,
            'filesize': os.path.getsize(path),
            'infected': json_obj['avast']['infected'],
            'result': json_obj['avast']['result']
        }
    except Exception:
        data = {
            'timestamp': datetime.now(),
            'time_elapsed': end-start,
            'filepath': path,
            'filesize': os.path.getsize(path),
            'infected': json_obj['avast']['infected'],
            'result': json_obj['avast']['result'],
            'exception': str(Exception)
        }
        pass

    return data

def putToES(json_data):
    es = Elasticsearch(http_auth=('elastic', 'changeme'))
    res = es.index(index="test-results", doc_type='test-result', id=uuid.uuid4(), body=json_data)

def runTests():
    count = 0
    while (count < 1):
        try:
            length = len(items)
            path_nr = random.randint(0,length-1)
            data = runVirusScanTest("../testfiles/" + items[path_nr])
            putToES(data)
            time.sleep(0.2)
        except Exception:
            print Exception
            pass

runTests()
```

Can you please look at this issue ?

**Comment by blacktop** [comment]
This is a great test.  

Have you also tried the other AVs and Avast is the only one with this issue or are you primarily interested only in Avast?

**Comment by jcajkovic** [comment]
Hi, I've test only the Avast. Well if this issue is Avast related than we are flexible to switch. However I do not have time to test all of them.

I forgot to mentioned that I changed the code for web service routine in go since I need this be able to communicate thru SSL as the files sent to scan can contain private sensitive information:
```
func webService() {
	router := mux.NewRouter().StrictSlash(true)
	router.HandleFunc("/scan", webAvScan).Methods("POST")
	log.WithFields(log.Fields{
		"plugin":   name,
		"category": category,
	}).Info("web service listening on port :443")
	log.Fatal(http.ListenAndServeTLS(":443", "/certificates/server.crt", "/certificates/server.key", router))
}
```

**Comment by blacktop** [comment]
I would be curious if this is specific to Avast could you test at least one more AV?

**Comment by jcajkovic** [comment]
Hi yes this weekend or next week I can test avast with not changed routine and also I will test kaspersky too.

**Comment by blacktop** [comment]
So I was not able to finish the Malice kaspersky AV because I cannot get a trial key for the corporate/business linux file server AV scanner.  I had a github user that thought they could get me a trial key, but hasn't responded yet.

https://github.com/maliceio/malice-av/issues/3

**Comment by jcajkovic** [comment]
than I will check some other just tell me which one I should try

**Comment by blacktop** [comment]
Maybe Avira? Maybe not that one requires a license key.

Zoner might be good?  It is one of the newer AVs I added.

**Comment by blacktop** [comment]
Here is the master list of my AV plugins: https://github.com/maliceio/malice-av/blob/master/README.md

The readme links to all the individual repos.

**Comment by jcajkovic** [comment]
Hi I checked the avast - your build and it suffer with the issue, on the other side I checked comodo which does not, so maybe it is not caused by your implementation of the service but by the avast. I'm going to test clamav, avg and escan (in progress) to see if those are not having the issue. What I seen till now is that avast have much better performance than others.

**Comment by jcajkovic** [comment]
escan does not have the issue, however I would like to test on bigger scale as the scanning time is much slower so I have to put more load on the service, to compensate the service performance.

**Comment by blacktop** [comment]
That is very interesting.  Maybe it is starting the avast service that is non-deterimistic `/etc/init.d/avast start`. I could add more checks to make sure it is running before scanning, but you said it was mixing up files with responses?  That sounds like Golang wasn't tracking http sessions properly?  Golang is very good at http so I would assume it would be on avast's side.

**Comment by blacktop** [comment]
Another idea, for the AV plugins at least, is when used as a web-service might be to start services/load definitions into memory before starting the HTTP web server?  That way it would hopefully make scanning much faster.

**Comment by jcajkovic** [comment]
Hi do you have any update on this ?

**Comment by jcajkovic** [comment]
Hi blacktop any update here ?

**Comment by blacktop** [comment]
Just to remind myself you are only interested in using the malice-av plugins as web-micro-services right?

**Comment by blacktop** [comment]
Also it looks like you were going to test `escan` on a "bigger scale" did you do that?  Is it important that you use Avast over the other AV plugins?

**Comment by jcajkovic** [comment]
Hi we need to have webservice which accept file and tells us if it is infected or no, it does not need to be the container or microservice. And Avast has nice pricing policy compared to the performance.

**Comment by blacktop** [comment]
So it sounds like you just need to talk to Avast tech support?
